apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openconnect-gateway
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/Arbuzov/local-cluster-argo.git
    targetRevision: main
    path: networking/openconnect-gateway/chart
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
