apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wg-vless-gateway
  namespace: argo-cd
spec:
  project: networking
  source:
    repoURL: https://github.com/Arbuzov/home-cluster-helm.git
    targetRevision: HEAD
    path: arbuzov/networking/wg-vless-gateway
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vpn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
