apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wstunnel
  namespace: argo-cd
spec:
  project: networking
  source:
    repoURL: https://github.com/Arbuzov/home-cluster-helm.git
    targetRevision: HEAD
    path: arbuzov/networking/wstunnel
  destination:
    server: https://kubernetes.default.svc
    namespace: wstunnel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
