apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp-atlassian-confluence
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mcp
  source:
    repoURL: https://arbuzov.github.io/mcp-helm/
    targetRevision: 0.2.28
    chart: mcp-atlassian
    helm:
      values: |
        extraArgs:
          - --transport
          - streamable-http
          - --stateless
        image:
          repository: ghcr.io/arbuzov/mcp-atlassian
          tag: 0.21.1-fork.1
        env:
          CONFLUENCE_URL: https://confluence.spacebridge.com
          CONFLUENCE_SSL_VERIFY: 'false'
          MCP_VERY_VERBOSE: true
          MCP_LOGGING_STDOUT: true
          TRANSPORT: streamable-http
        envSecrets:
          CONFLUENCE_USERNAME:
            name: mcp-atlassian-confluence-credentials
            key: CONFLUENCE_USERNAME
          CONFLUENCE_API_TOKEN:
            name: mcp-atlassian-confluence-credentials
            key: CONFLUENCE_API_TOKEN
        livenessProbe:
          enabled: false
        readinessProbe:
          enabled: false
        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/auth-type: basic
            nginx.ingress.kubernetes.io/auth-secret: mcp-basic-auth
            nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
            nginx.ingress.kubernetes.io/rewrite-target: /mcp/confluence$2
          path: /mcp/confluence
          hosts:
            - dev.whitediver.keenetic.link
            - "*"
        sidecars:
          - name: vpn-sidecar
            image: docker.io/aw1cks/openconnect
            env:
              - name: URL
                value: "https://asa1.spacebridge.com"
              - name: AUTH_GROUP
                value: VPN_THROUGHT
              - name: EXTRA_ARGS
                value: '--servercert pin-sha256:uUSuxlR7/XsvkUStQFLeE0rJNrPf25XfPNMEbPLFKVs='
              - name: USER
                valueFrom:
                  secretKeyRef:
                    name: mcp-atlassian-vpn-credentials
                    key: USERNAME
              - name: PASS
                valueFrom:
                  secretKeyRef:
                    name: mcp-atlassian-vpn-credentials
                    key: PASSWORD
            securityContext:
              privileged: true
              capabilities:
                add:
                  - NET_ADMIN
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
