apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp-atlassian-jira
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mcp
  source:
    repoURL: https://arbuzov.github.io/mcp-helm/
    targetRevision: 0.2.28
    chart: mcp-atlassian
    helm:
      values: |
        extraArgs:
          - --transport
          - streamable-http
          - --stateless
        image:
          repository: ghcr.io/arbuzov/mcp-atlassian
          tag: 0.21.1-fork.1
        env:
          MCP_VERY_VERBOSE: true
          MCP_LOGGING_STDOUT: true
          TRANSPORT: streamable-http
        envSecrets:
          JIRA_URL:
            name: mcp-corp-config
            key: JIRA_URL
          JIRA_USERNAME:
            name: mcp-atlassian-jira-credentials
            key: JIRA_USERNAME
          JIRA_API_TOKEN:
            name: mcp-atlassian-jira-credentials
            key: JIRA_API_TOKEN
        livenessProbe:
          enabled: false
        readinessProbe:
          enabled: false
        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/auth-type: basic
            nginx.ingress.kubernetes.io/auth-secret: mcp-basic-auth
            nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
            nginx.ingress.kubernetes.io/rewrite-target: /mcp/jira$2
          path: /mcp/jira
          hosts:
            - dev.whitediver.keenetic.link
            - "*"
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
